models/AdminBaseModel.php
<?php

namespace app\models;

use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;


abstract class AdminBaseModel extends ActiveRecord
{
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }
}

models/Bill.php
<?php

namespace app\models;

use Yii;
use yii\base\Exception;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "posts".
 *
 * @property integer $id
 * @property string $vendor
 * @property string $price
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $category_id
 * @property bool $is_paid

 *
 * @property Category $category
 */
class Bill extends AdminBaseModel
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bills';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['vendor', 'price', 'category_id'], 'required'],
            [['is_paid', 'created_at', 'updated_at', 'category_id'], 'integer'],
            [['vendor'], 'string', 'max' => 255],
            [['price'], 'string', 'max' => 255],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(),
                'targetAttribute' => ['category_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'vendor' => 'Vendor',
            'price' => 'Price',
            'created_at' => 'Date',
            'updated_at' => 'Updated At',
            'category_id' => 'Category',
            'is_paid' => 'Is Paid',
        ];
    }
      /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }
}

models/Category.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "categories".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property Bill[] $bills
 */
class Category extends AdminBaseModel
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'categories';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['created_at', 'updated_at'], 'integer'],
            [['name'], 'string', 'max' => 100],
            [['name', 'description'], 'required'],
            [['description'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBills()
    {
        return $this->hasMany(Bill::className(), ['category_id' => 'id']);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Bill;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\ActiveRecord;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\widgets\ActiveForm;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $bills = new ActiveDataProvider([
            'query' => Bill::find()->orderBy('created_at desc'),
            'pagination' => [
                'pagesize' => 2,
            ],]);

        return $this->render('index', [
            'bills' => $bills
        ]);
    }

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreateBill()
	{
		$model = new Bill();

		if (Yii::$app->request->isAjax AND $model->load(Yii::$app->request->post())) {
			Yii::$app->response->format = Response::FORMAT_JSON;
			return ActiveForm::validate($model);
		}

		if ($model->load(Yii::$app->request->post()) && $model->save()) {
			return $this->redirect(['index']);
		} else {
			return $this->render('create-bill', [
				'model' => $model,
			]);
		}
	}

	/**
	 * Updates an existing model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionUpdateBill($id)
	{
		$model = $this->findModel($id);

		if (Yii::$app->request->isAjax AND $model->load(Yii::$app->request->post())) {
			Yii::$app->response->format = Response::FORMAT_JSON;
			return ActiveForm::validate($model);
		}

		if ($model->load(Yii::$app->request->post()) && $model->save()) {
			return $this->redirect(['index']);
		} else {
			return $this->render('update-bill', [
				'model' => $model,
			]);
		}
	}

	/**
	 * Finds the Category model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param integer $id
	 * @return ActiveRecord
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id)
	{
		if (($model = Bill::findOne($id)) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException('The requested page does not exist.');
		}
	}
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\components\AsideBarWidget;
use app\components\SiteMenu;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
</head>
<body>
<?php $this->beginBody() ?>
<header id="header">
    <?= SiteMenu::widget() ?>
</header>
<!--/#header-->

<section id="page-breadcrumb">
    <div class="vertical-center sun">
        <div class="container">
            <div class="row">
                <div class="action">
                    <div class="col-sm-12">
                        <h1 class="title"><?= Yii::$app->params['siteName'] ?></h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--/#page-breadcrumb-->
<section id="blog" class="padding-top">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <?= $content ?>
            </div>
        </div>
    </div>
</section>
<!--/#blog-->

<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center bottom-separator">
                <img src="/images/home/under.png" class="img-responsive inline" alt="">
            </div>
            <div class="col-md-offset-3 col-md-3 col-sm-12">
                <div class="contact-info bottom">
                    <h2>Contacts</h2>
                    <address>
                        E-mail: <a href="mailto:someone@example.com">email@email.com</a> <br>
                        Phone: +1 (123) 456 7890 <br>
                        Fax: +1 (123) 456 7891 <br>
                    </address>
                </div>
            </div>
            <div class="col-md-3 col-sm-12">
                <div class="contact-info bottom">
                    <h2>Address</h2>
                    <address>
                        Unit C2, St.Vincent's Trading Est., <br>
                        Feeder Road, <br>
                        Bristol, BS2 0UY <br>
                        United Kingdom <br>
                    </address>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="copyright-text text-center">
                    <p>&copy; Your Company 2014. All Rights Reserved.</p>
                    <p>Designed by <a target="_blank" href="http://www.themeum.com">Themeum</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>
<!--/#footer-->


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/_form.php
<?php

use app\models\Category;
use app\models\Tag;
use dosamigos\selectize\SelectizeDropDownList;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\redactor\widgets\Redactor;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Post */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="bill-form">

    <?php $form = ActiveForm::begin([
        'enableAjaxValidation' => true,
        'enableClientValidation' => false,
    ]); ?>

    <div class="col-xs-12 col-md-6">

        <?= $form->field($model, 'vendor')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'price')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'is_paid')->checkbox() ?>

        <?= $form->field($model, 'category_id')
            ->dropDownList(ArrayHelper::map(Category::find()->all(), 'id', 'name'), [
                'prompt' => 'Select post category'
            ]) ?>
    </div>

    <div class="form-group col-xs-12">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ?
            'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/site/_short_bill_view.php
<?php

/** @var \app\models\Bill $model */
use app\models\Bill;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

?>
<div class="col-sm-12 col-md-12">
    <div class="single-blog single-column">
        <div class="post-thumb">
            <a href="blogdetails.html">
                <!--                <img src="images/blog/7.jpg" class="img-responsive" alt="">-->
            </a>
            <div class="post-overlay">
                <span class="uppercase"><a href="#">14 <br><small>Feb</small></a></span>
            </div>
        </div>
        <div class="post-content overflow">
            <h2 class="post-title bold"><?= Html::a($model->id, [
                    'site/bill',
                    'id' => $model->id
                ]) ?></h2>
	        <span class="label <?= $model->is_paid ? 'label-success' : 'label-danger'?>"> <?= $model->is_paid ? 'Paid' : 'Not Paid'?></span>
            <h3 class="post-author">Date <?= date('l jS \of F Y h:i:s A', $model->created_at) ?>
            </h3>
            <p>Vendor:<?= $model->vendor ?></p>
            <p>Price: <?= $model->price ?></p>
            <?= Html::a('Update', ['site/update-bill', 'id' => $model->id],
                ['class' => 'read-more']) ?>
            <div class="post-bottom overflow">
                <ul class="nav navbar-nav post-nav">
                    <li><?= Html::a('<i class="fa fa-list-ul"></i>' . $model->category->name,
                            ['#']) ?></li>
                </ul>
            </div>
        </div>
    </div>
</div>

views/site/category.php
<?php

use yii\widgets\ListView;

/** @var \yii\debug\models\timeline\DataProvider $categoryPosts */
/** @var string $categoryName */

$this->title = $categoryName;

?>
<h3>All posts by Category: <strong><?= $categoryName?></strong></h3>
<div class="row">
    <?= ListView::widget([
        'dataProvider' => $categoryPosts,
        'pager' => [
            'hideOnSinglePage' => true,
        ],
        'layout' => '{items} <div class="blog-pagination">{pager}</div>',
        'summary'=>'',
        'itemView' => '_short_post_view'
    ])?>
</div>

views/site/create-bill.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Bill */

$this->title = 'Create Bill';
$this->params['breadcrumbs'][] = ['label' => 'Bills', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="bill-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\widgets\ListView;

$this->title = 'Blog';

/** @var \yii\debug\models\timeline\DataProvider $latestPosts */
?>

<div class="row">
    <?= ListView::widget([
        'dataProvider' => $bills,
        'pager' => [
            'hideOnSinglePage' => true,
        ],
        'layout' => '{items} <div class="blog-pagination">{pager}</div>',
        'summary'=>'',
        'itemView' => '_short_bill_view'
    ])?>
</div>

views/site/update-bill.php
<?php

use app\components\InfoWidget;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Bill */

$this->title = 'Update Bill: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Bills', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="bill-update">

    <h1><?= Html::encode($this->title) ?> <?= $model->isNewRecord ? '' : InfoWidget::widget(['model' => $model])?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>